services:
  gemini:
    user: "1000:1000"
    image: gemini:LATEST
    stdin_open: true
    tty: true
    container_name: gemini
    build:
      context: .
    volumes:
      - ./workspace:/workspace
